### ISSUE TITLE
Publish Python 3.12 wheel?

### ISSUE THREAD

**Issue by scottbelden** [milesgranger/pyrus-cramjam#112]
I'm hoping to be able to use this library rather than `python-snappy` as this seems easier to install (whereas `python-snappy` needs system installs). But currently when trying to install on Python 3.12 it tries to install the tar.gz because no wheel exists. Would it be possible to create a Python 3.12 wheel on the next release?

Thanks!

**Comment by martindurant** [comment]
@scottbelden : just to let you know that there is a half-hatched plan to have python-snappy simply require and use this library in the future and be otherwise retired. It's just a question of time & effort.

**Comment by scottbelden** [comment]
> @scottbelden : just to let you know that there is a half-hatched plan to have python-snappy simply require and use this library in the future and be otherwise retired. It's just a question of time & effort.

Is there an existing github issue that talks about this so I can subscribe to see if/when that happens?

**Comment by martindurant** [comment]
Originally https://github.com/andrix/python-snappy/issues/91 but I have a feeling there must be something more recent

**Comment by milesgranger** [comment]
FWIW, first I heard about it was from https://github.com/andrix/python-snappy/issues/124#issuecomment-1486886986.

**Comment by milesgranger** [comment]
[Wheels are on PyPI](https://pypi.org/project/cramjam/#files). Thank you!

**Comment by scottbelden** [comment]
Thank you!
