### ISSUE TITLE
failure of compress_into

### ISSUE THREAD

**Issue by martindurant** [milesgranger/pyrus-cramjam#31]
```
data = b"oh what a beautiful morning, oh what a beautiful day!!" * 5000000   # 270000000 bytes
x = np.zeros(270000000, dtype='uint8') # plenty of space
size = cramjam.gzip.compress_into(data, x)
cramjam.gzip.decompress(x.tobytes()[:size])
```
gives `DecompressionError: corrupt deflate stream`. The value of `size`, 15787, is much smaller than the size you get with the compression function(s), 785746.

**Comment by milesgranger** [comment]
Nice, I've gotten the output bytes corrected, but seems the header is invalid. :thinking: 
Thanks for the report. :+1:
