### ISSUE TITLE
test_bench.py: Snappy tests fail

### ISSUE THREAD

**Issue by veprbl** [milesgranger/pyrus-cramjam#60]
Something I've stumbled upon packaging this for nixpkgs https://github.com/NixOS/nixpkgs/pull/124862.
Here is the build log https://gist.github.com/veprbl/345d882b01923f31fcfc75c1238d305b
Fastparquet's round trip tests seem to pass just fine. Perhaps they don't use this code path?

**Comment by veprbl** [comment]
Please disregard previous log, it was build without `python-snappy`. Here is a corrected one: https://gist.github.com/veprbl/288bc21cede2c2aa676362ff0e033e0b

**Comment by martindurant** [comment]
The log is quite hard to read, but are you attempting to reverse `cramjam.snappy.compress` with `decompress_raw_into`? The pairings are
- compress_raw/decompress_raw[_into] 
- compress/decompress[_into] (also known as the "framed" format in some places)

**Comment by messense** [comment]
Reproduced in https://github.com/milesgranger/pyrus-cramjam/runs/2707922230?check_suite_focus=true

**Comment by milesgranger** [comment]
Thanks for the report, my mistake of creating some bad logic in the test, but @messense nailed it. 
Don't hesitate to report back should you run into any other issues!

**Comment by milesgranger** [comment]
@veprbl do you want a new release (2.3.2) for this change? I see your PR there is pulling from PyPI.

**Comment by veprbl** [comment]
@messense @milesgranger Thank you for the quick resolution! We certainly would not mind a release if that's not an inconvenience for you. Otherwise, we can pull in the relevant commits.

**Comment by milesgranger** [comment]
No problem at all. [v2.3.2](https://github.com/milesgranger/pyrus-cramjam/releases/tag/v2.3.2) is made and [should be on PyPI shortly](https://github.com/milesgranger/pyrus-cramjam/actions/runs/892243883)
