### ISSUE TITLE
cargo_audit does not like brotli-sys

### ISSUE THREAD

**Issue by bnavigator** [milesgranger/pyrus-cramjam#86]
When trying to package pyrus-cramjam for openSUSE Tumbleweed, I get this:

```
info:obs-service-cargo_audit: Running OBS Source Service : obs-service-cargo_audit
ERROR:obs-service-cargo_audit:  possible vulnerabilties: 1
ERROR:obs-service-cargo_audit: /tmp/tmptxa26w30/pyrus-cramjam/Cargo.lock
ERROR:obs-service-cargo_audit: For more information you SHOULD inspect the output of cargo audit manually
ERROR:obs-service-cargo_audit: * RUSTSEC-2021-0131 -> crate: brotli-sys, cvss: None, class: ['memory-corruption']
ERROR:obs-service-cargo_audit: ⚠️  Vulnerabilities may have been found. You must review these.
Aborting: service call failed:  /usr/lib/obs/service/cargo_audit --srcdir pyrus-cramjam --outdir /home/ben/src/osc/home:bnavigator:branches:devel:languages:python:numeric/python-cramjam/tmpegree2c6.cargo_audit.service
```

[obs-service-cargo_audit](https://github.com/openSUSE/obs-service-cargo_audit) uses the local Cargo.lock file to determine if the related sources in a Rust application have known security vulnerabilities. If vulnerabilities are found, the source service will alert allowing you to update and help upstream update their sources.

https://github.com/milesgranger/pyrus-cramjam/blob/29d9e3b4e1e116761637b7a0f3ac8830f2f1541b/Cargo.lock#L23-L31

The cited security advisory is here: https://rustsec.org/advisories/RUSTSEC-2021-0131.html, https://github.com/bitemyapp/brotli2-rs/issues/45

**Comment by milesgranger** [comment]
Thanks. As there is no patched version as of now, I suspect this won't be solved soon. I'll look more deeply into possible alternatives as time permits.

**Comment by bnavigator** [comment]
From the advisory:

> An updated version of brotli-sys has not been released. If one cannot update the C library, its authors recommend to use the "streaming" API as opposed to the "one-shot" API, and impose chunk size limits.
> 
> In Rust the issue can be mitigated by migrating to the brotli crate, which provides a Rust implementation of Brotli compression and decompression that is not affected by this issue.

**Comment by milesgranger** [comment]
Thanks, I see that. It's what I meant as an alternative but haven't looked at the whole ecosystem since that was reported. Further, that was used in the first place because at the time of writing it looked more or less abandoned and/or was missing some features as I recall.

I'm away from my computer but rest assured this will be addressed. Thank you again for the thorough report.
