### ISSUE TITLE
Please consider adding license metadata to PyPI

### ISSUE THREAD

**Issue by asmith26** [milesgranger/pyrus-cramjam#89]
Hi there,

I'm looking at using [fastparquet](https://github.com/dask/fastparquet/) which seems to have a [dependency on cramjam](https://github.com/dask/fastparquet/blob/b22b02f12e4609161af97740dbdef4a59bc56fbc/requirements.txt#L3). I'm also using [`liccheck`](https://github.com/dhatim/python-license-check) to check any python packages we use are compatible with our license needs. It looks like this package is licensed under [MIT](https://github.com/milesgranger/pyrus-cramjam/blob/master/LICENSE), however because this information is not included in the PyPI package, `liccheck` is flagging cramjam as "unknown license" (see the META section of [cramjam](https://pypi.org/project/cramjam/) compared with e.g. [fastparquet](https://pypi.org/project/fastparquet/)).

I'm not familiar with maturin (which I think is used to build this package), but possibly you need to add something like https://www.maturin.rs/metadata.html#python-project-metadata or https://stackoverflow.com/a/73274312/5179470 ?

Many thanks for any help, and for this great package! :)

**Comment by milesgranger** [comment]
Thank you for the report and helpful information, much appreciated. :)

**Comment by milesgranger** [comment]
Once https://github.com/milesgranger/pyrus-cramjam/actions/runs/3428734703 is finished, 2.6.2 should satisfy your needs.
