### ISSUE TITLE
use with cargo?

### ISSUE THREAD

**Issue by martindurant** [milesgranger/pyrus-cramjam#97]
How would I import this as a crate in other python-facing rust package? I would like to use RustyBuffer as a zero-copy way of passing read()-able byte chunks to python within rfsspec. Later, I would also use the (stream) de/compressors. Just naively adding `cramjam` into my Cargo.toml causes a big long list of compiler errors related to linker symbols.

**Comment by milesgranger** [comment]
You're likely blocked by https://github.com/PyO3/pyo3/issues/1444

**Comment by milesgranger** [comment]
Closing this, as I think #101 solves the last portion of you wanted to use the stream de/compressors; and nothing I can do about the first but see you've got it in rfsspec, and suppose you too, can use the buffer protocol to pass cramjam Buffer or otherwise to it I think.
