### ISSUE TITLE
macos wheels aren't built for the macos versions they advertise

### ISSUE THREAD

**Issue by markopy** [milesgranger/pyrus-cramjam#98]
The macos wheels on pypi indicate that they are for macos version >=10.7 and they get installed as such but they are actually built for macos 11.0.

Importing the module on macos 10.13.6 results in
```
ImportError: dlopen(<snip>/.venv/lib/python3.9/site-packages/cramjam/cramjam.cpython-39-darwin.so, 2): Symbol not found: ____chkstk_darwin
  Referenced from: <snip>/.venv/lib/python3.9/site-packages/cramjam/cramjam.cpython-39-darwin.so (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
```

**Comment by milesgranger** [comment]
@messense have you seen this before?

**Comment by messense** [comment]
You need to set `MACOSX_DEPLOYMENT_TARGET=10.7` to make sure of it when building.

**Comment by messense** [comment]
It's already set by default in maturin 0.14.x: https://github.com/PyO3/maturin/pull/1251

Upgrade and rebuild should resolve this issue.

**Comment by milesgranger** [comment]
Thanks @messense! I'll ensure to do this next release. @markopy does the releases on conda-forge work for you? Suspect maybe it's the same issue there. Will try to make a new release later today.

**Comment by milesgranger** [comment]
```
pip install cramjam==2.7.0rc1
```

Let me know if that works for you. Will wait a bit on a full 2.7.0 release as I'm wanting to get some other stuff in.

**Comment by markopy** [comment]
The new 2.7.0rc1 version works as expected. Also checked 2.6.2 on conda and that one works as well.

Awesome turnaround time guys! Wasn't expecting to have this all fixed when I wake up. Thanks a lot!
